{% set version = "0.13.1" %}

package:
  name: conda-build-all
  version: "{{ version }}"

source:
    fn: conda-build-all_v{{ version }}.tar.gz
    url: https://github.com/SciTools/conda-build-all/archive/v{{version}}.tar.gz
    sha256: 644b7ea3b7bdec66f7dfb10f5d1dbd815afd55fa4d23ecbbfae04ff251ba9a0f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - gitpython
    - conda >4
    - conda-build >=1.20.2
    - anaconda-client
    - mock

test:
  imports:
    - conda_build_all
  commands:
    - conda build-all --version

about:
  license: BSD 3-clause
  home: https://github.com/scitools/conda-build-all
  summary: conda build-all is a conda subcommand which allows multiple distributions to be built (and uploaded) in a single command

extra:
  recipe-maintainers:
    - pelson
