{% set version = "0.11.0" %}

package:
  name: conda-build-all
  version: "{{ version }}"

source:
    fn: conda-build-all_v{{ version }}.tar.gz
    url: https://github.com/SciTools/conda-build-all/archive/v{{version}}.tar.gz
    sha1: f7d1feb3e1f767abbb147ba58447a756b63de59e

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - gitpython
    - conda
    - conda-build
    - anaconda-client
    - mock  # [py<33]

test:
  imports:
    - conda_build_all
  commands:
    - conda build-all --version
    - conda buildall --version
    - conda-build-all --version

about:
  license: BSD 3-clause
  home: https://github.com/scitools/conda-build-all
