{% set version = "0.10.0" %}

package:
  name: conda-build-all
  version: "{{ version }}"

source:
    fn: conda-build-all_v{{ version }}.tar.gz
    url: https://github.com/SciTools/conda-build-all/archive/v{{version}}.tar.gz
    sha1: 1ef9926fbbf4a53f17916e6a01e417bf13668cd6

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - gitpython
    - conda
    - conda-build
    - anaconda-client

test:
  imports:
    - conda_build_all
  commands:
    - conda buildall --version
    - conda-build-all --version

about:
  license: BSD-3
  home: https://github.com/scitools/conda-build-all
